[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v6.0.0"

[[constraint]]
  name = "github.com/manifoldco/go-manifold"
  version = "v0.9.2"
